CREATE TABLE IF NOT EXISTS contact_enquiries (
 id BIGSERIAL PRIMARY KEY,
 name VARCHAR(120) NOT NULL,
 email VARCHAR(180) NOT NULL,
 phone VARCHAR(40),
 company VARCHAR(180),
 service VARCHAR(120),
 message TEXT NOT NULL,
 status VARCHAR(20) NOT NULL DEFAULT 'NEW',
 created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE IF NOT EXISTS newsletter_subscribers (
 id BIGSERIAL PRIMARY KEY,
 email VARCHAR(180) UNIQUE NOT NULL,
 created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);
